## Unnamed Functions (i.e. lambda functions)

In [94]:
#Define a typical function several ways
function f1(x)
    return 2x + 1
end
f2(x) = 2x + 1
f3 = x -> 2x + 1 #could assign to a variable, but don't need to

#Mapping this across a vector (i.e. [f1(1) f1(2) f1(3)] etc.) shows all the same
@show map(f1, [1 2 3])
@show map(f2, [1 2 3])
@show map(f3, [1 2 3]) #Note: create an unnamed function x mapping to 2 * x + 1
#Or using directly assigning 
map(x -> 2x + 1, [1 2 3])

map(f1, [1 2 3]) = [3 5 7]
map(f2, [1 2 3]) = [3 5 7]
map(f3, [1 2 3]) = [3 5 7]


1×3 Array{Int64,2}:
 3  5  7

## Functions of Functions (e.g. map)

In [79]:
twice(f,x) = f(f(x))

twice (generic function with 1 method)

In [80]:
f(x) = x^2
twice(f, 2.0)
twice(x -> x^2, 2.0) #Anonymous function

16.0

# Higher Order Functions

In [90]:
function makedouble(g)
    return x -> 2 * g(x) #i.e. returns a function which uses f
end
h = makedouble(f) #Use our quadratic, returns a new function which doubles the result
h(2)

8

## Tuples and Named Tuples

In [93]:
using NamedTuples #Won't need in Julia v0.7
#A tuple is a collection of several things, which can have different types
tup1 = (1.0, "a string")
@show tup1

#A named tuple is a collection where we assign names to each of them.
#Prefix with @NT for now, but won't be necessary in Julia 0.7
tup2 = @NT(a = 1.0, b = "a string")
@show tup2

#Access with the name
@show tup2.a
@show tup2.b

tup1 = (1.0, "a string")
tup2 = (a = 1.0, b = "a string")
tup2.a = 1.0
tup2.b = "a string"


"a string"

## Array Comprehensions and Broadcasting

In [28]:
y = ones(5,1)

for i in 1:5
    y[i] = f(i)
end
y

5×1 Array{Float64,2}:
  1.0
  4.0
  9.0
 16.0
 25.0

In [26]:
f.(1:5) #Broadcast

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [32]:
2.*(y .+ f.(1:5))

5×1 Array{Float64,2}:
   4.0
  16.0
  36.0
  64.0
 100.0

In [36]:
[f(x) for x in 1:5] #comprehension

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [38]:
[(x + y, x * y) for x in 1:5, y in 1:5] #Make a multiplication and addition table

5×5 Array{Tuple{Int64,Int64},2}:
 (2, 1)  (3, 2)   (4, 3)   (5, 4)   (6, 5)  
 (3, 2)  (4, 4)   (5, 6)   (6, 8)   (7, 10) 
 (4, 3)  (5, 6)   (6, 9)   (7, 12)  (8, 15) 
 (5, 4)  (6, 8)   (7, 12)  (8, 16)  (9, 20) 
 (6, 5)  (7, 10)  (8, 15)  (9, 20)  (10, 25)

## Matrices and Dot Products

In [39]:
[1.0 2.0] * [2.0; 3.0] #Returns an array

1-element Array{Float64,1}:
 8.0

In [8]:
dot([1.0 2.0],[2.0; 3.0]) #Returns the dot product

8.0

In [40]:
#Can use the \cdot <tab> to create the dot product
[1.0 2.0] ⋅ [2.0; 3.0]

8.0

In [45]:
P = [0.6 .4;
    .2 .8];
ϕ0 = [1.0 0.0];

#Calculate the transition dynamics of the markov chain
ϕt = [ϕ0 * P^j for j in 0:5]

#Plot 
using Plots
gr()
plot([ϕt[j][1] for j in 1:6]) #Gets the first one.
# or could combine in a comprehension
plot([ [1.0;0.0] ⋅ (ϕ0 * P^j) for j in 1:5])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 0.35 
 
 
 0.40 
 
 
 0.45 
 
 
 0.50 
 
 
 0.55 
 
 
 
 
 
 
 y1

## Interpolation

In [52]:
using QuantEcon
n = 5
xvalues = linspace(0, 1.0, n) #grid over values.
@show collect(xvalues)
f_raw(x) = x^2
yvalues = f_raw.(xvalues)

collect(xvalues) = [0.0, 0.25, 0.5, 0.75, 1.0]


5-element Array{Float64,1}:
 0.0   
 0.0625
 0.25  
 0.5625
 1.0   

In [53]:
# Linear interpolation returns a function (i.e. like a higher order function)
f_int = LinInterp(xvalues, yvalues) #Creates a "function" which interpolates that data
f_int(0.2)
f_int.([0.21, 0.35, 0.5])

3-element Array{Float64,1}:
 0.0525
 0.1375
 0.25  

In [56]:
xdata = 0.0:0.01:1.0
ydata = [f_raw.(xdata), f_int.(xdata)]
plot(xdata, ydata)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip6502)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.4745,375.869 37.9529,375.832 43.4313,375.723 48.9097,375.541 54.3881,375.286 59.8665,374.959 65.3449,374.558 70.8233,374.085 76.3017,373.539 81.7801,372.92 
 87.2585,372.228 92.7369,371.464 98.2153,370.626 103.694,369.716 109.172,368.733 114.651,367.677 120.129,366.549 125.607,365.347 131.086,364.073 136.564,362.726 
 142.043,361.306 147.521,359.814 152.999,358.248 158.478,356.61 163.956,354.899 169.435,353.115 174.913,351.258 180.391,349.329 185.87,347.327 191.348,345.251 
 196.827,343.103 202.305,340.883 207.783,338.589 213.262,336.223 218.74,333.784 224.219,331.272 229.697,328.687 235.175,326.029 240.654,323.299 246.132,320.496 
 251.611,317.619 257.089,314.671 262.567,311.649 268.046,308.554 273.524,305.387 279.003,302.147 284.481,298.834 289.96,295.448 295.438,291.99 300.916,288.458 
 306.395,284.854 311.873,281.177 317.352,277.427 322.83,273.605 328.308,269.709 333.787,265.741 339.265,261.7 344.744,257.586 350.222,253.4 355.7,249.14 
 361.179,244.808 366.657,240.403 372.136,235.925 377.614,231.374 383.092,226.751 388.571,222.054 394.049,217.285 399.528,212.443 405.006,207.528 410.484,202.541 
 415.963,197.48 421.441,192.347 426.92,187.141 432.398,181.862 437.876,176.511 443.355,171.086 448.833,165.589 454.312,160.019 459.79,154.376 465.268,148.66 
 470.747,142.872 476.225,137.01 481.704,131.076 487.182,125.069 492.66,118.99 498.139,112.837 503.617,106.612 509.096,100.313 514.574,93.9424 520.053,87.4986 
 525.531,80.982 531.009,74.3925 536.488,67.7303 541.966,60.9952 547.445,54.1873 552.923,47.3066 558.401,40.3531 563.88,33.3268 569.358,26.2277 574.837,19.0558 
 580.315,11.811 
 "/>
<polyline clip-path="url(#clip6502)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.4745,375.869 37.9529,374.959 43.4313,374.048 48.9097,373.138 54.3881,372.228 59.8665,371.318 65.3449,370.408 70.8233,369.498 76.3017,368.588 81.7801,367.677 
 87.2585,366.767 92.7369,365.857 98.2153,364.947 103.694,364.037 109.172,363.127 114.651,362.217 120.129,361.306 125.607,360.396 131.086,359.486 136.564,358.576 
 142.043,357.666 147.521,356.756 152.999,355.846 158.478,354.935 163.956,354.025 169.435,353.115 174.913,350.385 180.391,347.654 185.87,344.924 191.348,342.193 
 196.827,339.463 202.305,336.732 207.783,334.002 213.262,331.272 218.74,328.541 224.219,325.811 229.697,323.08 235.175,320.35 240.654,317.619 246.132,314.889 
 251.611,312.159 257.089,309.428 262.567,306.698 268.046,303.967 273.524,301.237 279.003,298.506 284.481,295.776 289.96,293.046 295.438,290.315 300.916,287.585 
 306.395,284.854 311.873,280.304 317.352,275.753 322.83,271.202 328.308,266.651 333.787,262.101 339.265,257.55 344.744,252.999 350.222,248.449 355.7,243.898 
 361.179,239.347 366.657,234.796 372.136,230.246 377.614,225.695 383.092,221.144 388.571,216.593 394.049,212.043 399.528,207.492 405.006,202.941 410.484,198.391 
 415.963,193.84 421.441,189.289 426.92,184.738 432.398,180.188 437.876,175.637 443.355,171.086 448.833,164.715 454.312,158.344 459.79,151.973 465.268,145.602 
 470.747,139.231 476.225,132.86 481.704,126.489 487.182,120.118 492.66,113.747 498.139,107.376 503.617,101.005 509.096,94.6341 514.574,88.2631 520.053,81.8921 
 525.531,75.5211 531.009,69.1501 536.488,62.7791 541.966,56.4081 547.445,50.0371 552.923,43.6661 558.401,37.2951 563.88,30.9241 569.358,24.553 574.837,18.182 
 580.315,11.811 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

## Expectations and Integration

In [57]:
using Distributions, StatPlots
#Create a binomial distribution.  Number of successes with n samples and p prob of success
N = 10
p = 0.5
dist = Binomial(N,p)
plot(dist)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
 0.00 
 
 
 0.05 
 
 
 0.10 
 
 
 0.15 
 
 
 0.20 
 
 
 0.25 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [65]:
NSamples = 100
draws = rand(dist, NSamples)
meandraw = mean(draws)
println("sample mean = $meandraw, actual mean = $(mean(dist))")

sample mean = 5.04, actual mean = 5.0


In [67]:
# Get the pdf of the distribution
distpdf = pdf.(dist, support(dist))

11-element Array{Float64,1}:
 0.000976563
 0.00976563 
 0.0439453  
 0.117188   
 0.205078   
 0.246094   
 0.205078   
 0.117188   
 0.0439453  
 0.00976563 
 0.000976563

In [68]:
#To find the expectation of a function, for example E( log(n+1) )
distpdf = pdf.(dist, support(dist))
@show  [log(n+1) for n = 0:N]
expec = [log(n+1) for n = 0:N] ⋅ distpdf

[log(n + 1) for n = 0:N] = [0.0, 0.693147, 1.09861, 1.38629, 1.60944, 1.79176, 1.94591, 2.07944, 2.19722, 2.30259, 2.3979]


1.7526393207741668

In [88]:
#Or calculating it from the mean of a function of all the draws.  Should converge if a LLN holds
expecrand = mean([log(n+1) for n in draws])

1.765820337785714